### ISSUE TITLE
Bug in maxpost predictions

### ISSUE THREAD

**Issue by benRenard** [BaM-tools/BaMit#1]
When attempting to run a maxpost prediction, the progress bar goes to 100% but after a little while the following error message appears: "An error occurred while trying to retrieve the results files..." (and then BaMit is "locked" with this error, impossible to delete the prediction and to move forward).

The problem only occurs with the maxpost prediction which has no uncertainty, so I'm guessing the problem is due to trying to read an envelop file that does not exist?

**Comment by IvanHeriver** [comment]
I reproduced the error. It is indeed, due to the absence of envelop files... I'll see what I can do to fix this bug asap.

**Comment by IvanHeriver** [comment]
This issue should now be fixed. @benRenard, can you update the following files on the server:  
- www/components/bamPrediction/bamPrediction.js 
- server/RBaM_BaMit.R 

I leave the issue open for now in case I missed something.

**Comment by benRenard** [comment]
Done and checked, problem is fixed.
